[phases.setup]
nixPkgs = ['nodejs_22', 'nginx']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build', 'cp nginx.conf dist/']

[start]
cmd = 'cd dist && nginx -c $(pwd)/nginx.conf -g "daemon off;"'